# EPEL/Remi/RPMforgeをインストールする
- name: additional yum repository install
  yum: name={{item}} state=present
  with_items:
    - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    # - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

# 明示的に指定したいのでenabledは全て0にする
- name: repository enabled
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
    # - rpmforge.repo
    - remi.repo