# wp-config.phpに記入するsaltの取得
- name: Fetch random salts for WordPress config
  become: no
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

# wp-config.phpをテンプレートからユーザーディレクトリにコピー
- name: Copy WordPress config file
  template: >-
    src=wp-config.php
    dest=/home/vagrant/

# wp-config.phpをドキュメントルートへコピー
- name: Copy WordPress config file
  shell: creates={{document_root}}{{wordpress_directory}}/wp-config.php cp /home/vagrant/wp-config.php {{document_root}}{{wordpress_directory}}/wp-config.php
