- name: install php packages
  yum: name={{item}} state=latest enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql
  notify:
    - restart apache
  tags: php
