# require modules install
- name: node | install ruby require modules
  yum: name={{ item }} state=latest
  become: yes
  with_items:
    - gcc
    - gcc-c++
    - make
  tags: node

# nodejs check installed
- name: node | check node js installed
  shell: /bin/bash -lc "node -v"
  register: node_installed
  ignore_errors: yes
  become: no
  tags: nodejs

# install Nodesource
- name: node | install node script
  shell: /bin/bash -lc "curl -sL http://nsolid-rpm.nodesource.com/nsolid_setup_1.x | sudo bash -"
  when: node_installed.rc != 0

# install Nodejs
- name: node | install nodejs
  yum: name=nodejs state=latest
  when: node_installed.rc != 0
  tags: nodejs
