---
- hosts: default
  become: yes
  gather_facts: yes

  # playbook の変数
  # role の変数を上書きする
  vars:
    # document root
    document_root: /var/www/html

    #### for Movable Type ####
    # Mtで使用するDB名
    mt_db_name:
    # Mtで使用するDBユーザー
    mt_db_user:
    # Mtで使用するDBのパスワード
    mt_db_password:

    # MTのコアファイルのURL
    mt_archive_url:
    mt_archive_filename: # like 'MTOS-5.2.13'

    #### for Wordpress ####
    # wordpressサイト名
    wordpress_site_name:

    # wordpressディレクトリ
    # コアファイルをサブディレクトリにインストールする場合は
    # /wpのような形式で指定する
    wordpress_directory: '' # like '/wp'

    # wordpressで使用するDBの設定
    wordpress_db_name:
    wordpress_db_user:
    wordpress_db_password:
    wordpress_db_prefix:

    # wordpressの管理ユーザーの設定
    wordpress_site_admin_user:
    wordpress_site_admin_password:
    wordpress_site_admin_email:

  # 実行されるロールの指定
  roles:
    - common
    - httpd
    - mysql
    - php
    # - ruby
    # - node
    # - wordpress
    # - perl
    # - movabletype
